plugin:

  # See https://k9scli.io/topics/plugins/
  raw-logs-follow:
    shortCut: Ctrl-L
    description: logs -f
    scopes:
    - po
    - deploy
    command: kubectl
    background: false
    args:
    - logs
    - -f
    - $NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
